build_targets:
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04.1
  name: default
  environment:
      - PGUSER=ci
      - PGPASSWORD=ci
      - PGHOST={{ .Containers.IP "db" }}
      - ENCRYPTION_KEY=abcdefghijklmn
      - DATABASE_URL=postgres://ci:ci@{{ .Containers.IP "db" }}:5432/travis_ci_test
  dependencies:
      containers:
        db:
          image: postgres:9.4
          environment:
            - POSTGRES_PASSWORD=ci
            - POSTGRES_USER=ci
            - POSTGRES_DB=travis_ci_test
          port_check:
            port: 5432
            timeout: 45
ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - ruby:2.5.3
  - node:10.15.1
